version: "3.9"  # 如果需要消除警告，可以升级到更高版本（如 3.9）

services:
  fastapi:
    build:
      context: .  # 构建上下文路径
    ports:
      - "8000:8000"  # 端口映射
    volumes:
      - .:/app  # 挂载当前目录到容器的 /app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload  # 启动命令
